version: '3.8'  # Specify the version of Docker Compose

services:
  image-finder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - API_URL=https://picsum.photos
      - IMG_WIDTH=400
